<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>spec.rb</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>RSpec3</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b((before|after|around|subject)\b(?![?!])|let!?)</string>
			<key>name</key>
			<string>keyword.other.rspec</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#behaviour</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#shared-behaviour</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#single-line-example</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pending</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#example</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expectations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#matchers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#receive-counts</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#deprecated</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>behaviour</key>
		<dict>
			<key>begin</key>
			<string>^\s*([fx])?(describe|context|feature)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.rspec.focus-or-xclude</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.rspec.behaviour</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(do)\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ruby.start-block</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.rspec.behaviour</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<key>deprecated</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.rspec.deprecated</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\.(should(_not)?|be_false|be_true)\s+</string>
				</dict>
			</array>
		</dict>
		<key>example</key>
		<dict>
			<key>begin</key>
			<string>^\s*([fx])?(it|specify|scenario)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.rspec.focus-or-xclude</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.rspec.example</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(do)\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ruby.start-block</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.rspec.example</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<key>expectations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?!&lt;\.)(expect|allow)(?=\x28|\s*\x7b)</string>
					<key>name</key>
					<string>keyword.other.rspec.expectation</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?&lt;=\x29|\x7d)\.to(_not)?\b)</string>
					<key>name</key>
					<string>keyword.other.rspec.expectation</string>
				</dict>
			</array>
		</dict>
		<key>matchers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\.|\s)(receive(_message_chain)?|with|and_return|and_yield|and_raise)(?=\x28|\s*\x7b)</string>
					<key>name</key>
					<string>keyword.other.rspec.matcher.mocks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\.|\s)(eq|change|from|to|by|all|be_within|of|respond_to|raise_(error|exception))(?=\x28|\s*\x7b)</string>
					<key>name</key>
					<string>keyword.other.rspec.matcher</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(be(_a(n(_(kind|instance)_of)?)?)?)\b</string>
					<key>name</key>
					<string>keyword.other.rspec.matcher.predicate</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(be_(nil|truthy|falsey))</string>
					<key>name</key>
					<string>keyword.other.rspec.matcher</string>
				</dict>
			</array>
		</dict>
		<key>pending</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.rspec.pending</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.c++</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(it|specify|scenario)\s+(.*\S)(?&lt;!do)\s*$</string>
			<key>name</key>
			<string>meta.rspec.pending</string>
		</dict>
		<key>receive-counts</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\.|\s)(once|twice)</string>
					<key>name</key>
					<string>keyword.other.rspec.receive-count.simple</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\.|\s)(exactly|at_(least|most))(?=\x28)</string>
					<key>name</key>
					<string>keyword.other.rspec.receive-count</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\.|\s)times)(?!\x28)</string>
					<key>name</key>
					<string>keyword.other.rspec.receive-count.sugar</string>
				</dict>
			</array>
		</dict>
		<key>shared-behaviour</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.rspec.shared-behavior</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.ruby</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(include_examples|it_behaves_like|it_should_behave_like)\s+(.*\S)(?&lt;!do)\s*$</string>
			<key>name</key>
			<string>meta.rspec.shared-behavior</string>
		</dict>
		<key>single-line-example</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.rspec.example</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(it|specify|scenario)\s*{</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ruby.rspec</string>
	<key>uuid</key>
	<string>4E4C3DA2-D04C-44CF-AAA5-60790EFF5009</string>
</dict>
</plist>
